name: Cargo CI 

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Cargo fmt 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup component add --toolchain ${{ matrix.toolchain }} rustfmt
    - run: cd server && cargo fmt --all --check

  build:
    name: Cargo build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup target add --toolchain ${{ matrix.toolchain }} ${{ matrix.target }}
    - run: cd server && cargo build --target ${{ matrix.target }}