name: Release 

on:
  push:
    tags:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Server build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make build-server
    - run: docker tag registry.mrfriendly.uk/wilford-server:latest registry.mrfriendly.uk/wilford-server:${{ github.ref_name }}
    - run: docker push registry.mrfriendly.uk/wilford-server:latest
    - run: docker push registry.mrfriendly.uk/wilford-server:${{ github.ref_name }}